# Generated by Django 5.2.9 on 2026-03-08 15:56

import app.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_type', models.CharField(choices=[('private', 'Private'), ('group', 'Group')], default='private', max_length=7)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_msg_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-last_msg_at'],
            },
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, default='')),
                ('categoria', models.CharField(max_length=100)),
                ('localizacao', models.CharField(blank=True, default='', max_length=300)),
                ('percentagem_iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('entrega_ativa', models.BooleanField(default=False)),
                ('levantamento_ativo', models.BooleanField(default=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='lojas/logos/%Y/%m/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='lojas/banners/%Y/%m/')),
                ('cor_primaria', models.CharField(default='#000000', max_length=7)),
                ('cor_secundaria', models.CharField(default='#ffffff', max_length=7)),
                ('layout_produtos', models.CharField(choices=[('grid', 'Grelha'), ('list', 'Lista')], default='grid', max_length=10)),
                ('ativa', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='LojaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo_layout', models.CharField(max_length=50)),
                ('imagem_preview', models.ImageField(blank=True, null=True, upload_to='templates/')),
                ('suporta_banner', models.BooleanField(default=True)),
                ('suporta_produtos_destaque', models.BooleanField(default=True)),
                ('suporta_sidebar', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Encomenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tipo_entrega', models.CharField(choices=[('entrega', 'Entrega ao domicílio'), ('levantamento', 'Levantamento em loja')], default='levantamento', max_length=15)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('preparando', 'Em preparação'), ('enviado', 'Enviado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=15)),
                ('morada_entrega', models.CharField(blank=True, default='', max_length=300)),
                ('notas', models.TextField(blank=True, default='')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encomendas', to='app.loja')),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Condutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_veiculo', models.CharField(blank=True, default='', max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condutores', to='app.loja')),
            ],
        ),
        migrations.AddField(
            model_name='loja',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lojas', to='app.lojatemplate'),
        ),
        migrations.CreateModel(
            name='MetodoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cartao', 'Cartão'), ('dinheiro', 'Dinheiro'), ('mbway', 'MBWay'), ('paypal', 'PayPal'), ('stripe', 'Stripe')], max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pagamento', to='app.loja')),
            ],
            options={
                'unique_together': {('loja', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='OpcaoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('tempo_estimado', models.CharField(blank=True, default='', max_length=100)),
                ('area_cobertura', models.CharField(blank=True, default='', max_length=300)),
                ('ativa', models.BooleanField(default=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes_entrega', to='app.loja')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('atribuido', 'Atribuído'), ('a_caminho', 'A caminho'), ('entregue', 'Entregue'), ('falhou', 'Falhou')], default='atribuido', max_length=15)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_entrega', models.DateTimeField(blank=True, null=True)),
                ('condutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas', to='app.condutor')),
                ('encomenda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrega', to='app.encomenda')),
                ('opcao_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.opcaoentrega')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('falhado', 'Falhado'), ('reembolsado', 'Reembolsado')], default='pendente', max_length=15)),
                ('referencia_transacao', models.CharField(blank=True, default='', max_length=255)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('encomenda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='app.encomenda')),
                ('metodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.metodopagamento')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, default='')),
                ('categoria', models.CharField(blank=True, default='', max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('sku', models.CharField(blank=True, default='', max_length=100)),
                ('ficheiro', models.FileField(blank=True, null=True, upload_to=app.models.produto_upload, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'mp4', 'webm', 'mov', 'mkv'])])),
                ('destaque', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='app.loja')),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ItemEncomenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('encomenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app.encomenda')),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('preco_custo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('preco_venda', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='app.loja')),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='app.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, default='', max_length=30)),
                ('morada', models.CharField(blank=True, default='', max_length=300)),
                ('foto', models.ImageField(blank=True, default='utilizadores/default.png', null=True, upload_to='utilizadores/%Y/%m/')),
                ('verificado', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='ativo', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='utilizador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='loja',
            name='dono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lojas', to='app.utilizador'),
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ficheiro', models.FileField(blank=True, null=True, upload_to=app.models.galeria_upload, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'mp4', 'webm', 'mov', 'mkv'])])),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='ativo', max_length=20)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('comentarios', models.PositiveIntegerField(default=0)),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='app.utilizador')),
            ],
        ),
        migrations.AddField(
            model_name='encomenda',
            name='comprador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encomendas', to='app.utilizador'),
        ),
        migrations.AddField(
            model_name='condutor',
            name='utilizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condutor_em', to='app.utilizador'),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=app.models.chat_upload)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.chatthread')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.utilizador')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrinhos', to='app.loja')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrinhos', to='app.utilizador')),
            ],
            options={
                'unique_together': {('utilizador', 'loja')},
            },
        ),
        migrations.CreateModel(
            name='ItemCarrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app.carrinho')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produto')),
            ],
            options={
                'unique_together': {('carrinho', 'produto')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='condutor',
            unique_together={('loja', 'utilizador')},
        ),
        migrations.CreateModel(
            name='ChatParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_read', models.DateTimeField(default=django.utils.timezone.now)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='app.chatthread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.utilizador')),
            ],
            options={
                'unique_together': {('thread', 'user')},
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True, default='')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('encomenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacao', to='app.encomenda')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='app.loja')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='app.utilizador')),
            ],
            options={
                'unique_together': {('utilizador', 'loja', 'encomenda')},
            },
        ),
        migrations.CreateModel(
            name='UtilizadorLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('dono', 'Dono'), ('gestor', 'Gestor'), ('staff', 'Staff'), ('contabilista', 'Contabilista'), ('condutor', 'Condutor')], default='staff', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='app.loja')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lojas_staff', to='app.utilizador')),
            ],
            options={
                'unique_together': {('loja', 'utilizador')},
            },
        ),
    ]
