# Generated by Django 5.2.9 on 2026-03-10 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tipoproduto_produto_atributos_produto_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaoGuardado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(max_length=255)),
                ('stripe_payment_id', models.CharField(max_length=255)),
                ('marca', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('amex', 'American Express'), ('other', 'Outro')], default='other', max_length=20)),
                ('ultimos_4', models.CharField(max_length=4)),
                ('mes_expiracao', models.PositiveSmallIntegerField()),
                ('ano_expiracao', models.PositiveSmallIntegerField()),
                ('predefinido', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to='app.utilizador')),
            ],
            options={
                'ordering': ['-predefinido', '-data_criacao'],
            },
        ),
    ]
