# Generated by Django 5.0 on 2026-03-29 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cartaoguardado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoproduto',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_produto', to='app.loja'),
        ),
        migrations.AlterField(
            model_name='tipoproduto',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='tipoproduto',
            unique_together={('loja', 'nome')},
        ),
    ]
