# Generated by Django 5.0 on 2026-03-29 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tipoproduto_loja_alter_tipoproduto_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrinho',
            name='atributos',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='itemencomenda',
            name='atributos',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
