# Generated by Django 5.0 on 2026-04-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_itemcarrinho_atributos_itemencomenda_atributos'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='role_admin',
            field=models.CharField(blank=True, choices=[('superadmin', 'Super Admin'), ('moderador', 'Moderador'), ('suporte', 'Suporte'), ('contabilista', 'Contabilista')], default=None, max_length=20, null=True),
        ),
    ]
