# Generated by Django 5.0 on 2026-04-02 11:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_utilizador_role_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='percentagem_comissao',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Percentagem de comissao cobrada pela plataforma', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.CreateModel(
            name='Comissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_encomenda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentagem', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_comissao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('liquidada', 'Liquidada')], default='pendente', max_length=15)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_liquidacao', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('encomenda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comissao', to='app.encomenda')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissoes', to='app.loja')),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
    ]
