# Generated by Django 5.0 on 2026-04-03 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('loja_pendente', 'Loja pendente de aprovação'), ('loja_aprovada', 'Loja aprovada'), ('loja_rejeitada', 'Loja rejeitada'), ('nova_encomenda', 'Nova encomenda'), ('stock_baixo', 'Stock baixo'), ('novo_staff', 'Novo membro de staff'), ('encomenda_atualizada', 'Encomenda actualizada'), ('entrega_atribuida', 'Entrega atribuída'), ('entrega_atualizada', 'Entrega actualizada'), ('encomenda_paga', 'Encomenda paga'), ('encomenda_enviada', 'Encomenda enviada'), ('encomenda_concluida', 'Encomenda concluída'), ('encomenda_cancelada', 'Encomenda cancelada')], max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField(blank=True, default='')),
                ('link', models.CharField(blank=True, default='', max_length=300)),
                ('lida', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='app.loja')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='app.utilizador')),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
    ]
