# Generated by Django 5.0 on 2026-04-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_notificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('loja_pendente', 'Loja pendente de aprovação'), ('comissao_recebida', 'Comissão recebida'), ('loja_aprovada', 'Loja aprovada'), ('loja_rejeitada', 'Loja rejeitada'), ('nova_encomenda', 'Nova encomenda'), ('pagamento_aprovado', 'Pagamento aprovado'), ('encomenda_concluida_loja', 'Encomenda concluída na loja'), ('encomenda_cancelada_loja', 'Encomenda cancelada na loja'), ('stock_baixo', 'Stock baixo'), ('novo_staff', 'Novo membro de staff'), ('avaliacao_recebida', 'Nova avaliação recebida'), ('entrega_atribuida', 'Entrega atribuída'), ('entrega_cancelada', 'Entrega cancelada'), ('encomenda_paga', 'Encomenda paga'), ('encomenda_enviada', 'Encomenda enviada'), ('encomenda_concluida', 'Encomenda concluída'), ('encomenda_cancelada', 'Encomenda cancelada'), ('encomenda_atualizada', 'Encomenda actualizada')], max_length=30),
        ),
    ]
