# Generated by Django 5.0 on 2026-04-04 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_notificacao_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='opcao_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encomendas', to='app.opcaoentrega'),
        ),
    ]
