# Generated by Django 5.0 on 2026-04-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_encomenda_opcao_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaoloja',
            name='oculta',
            field=models.BooleanField(default=False),
        ),
    ]
