# Generated by Django 5.0 on 2026-04-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_avaliacaoloja_oculta'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='politica_devolucao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='loja',
            name='politica_privacidade',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='loja',
            name='termos_servico',
            field=models.TextField(blank=True, default=''),
        ),
    ]
