# Generated by Django 5.0 on 2026-04-10 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_categoriadestaque'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriadestaque',
            options={'ordering': ['ordem']},
        ),
        migrations.RemoveField(
            model_name='categoriadestaque',
            name='nome',
        ),
        migrations.AlterField(
            model_name='categoriadestaque',
            name='icone',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.CreateModel(
            name='CategoriaLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('icone', models.CharField(blank=True, default='📂', max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='app.loja')),
            ],
            options={
                'ordering': ['ordem', 'nome'],
                'unique_together': {('loja', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='categoriadestaque',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destaques', to='app.categorialoja'),
        ),
        migrations.AddField(
            model_name='produto',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='produtos', to='app.categorialoja'),
        ),
    ]
