# Generated by Django 5.0 on 2026-04-10 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_categoria_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
    ]
