# Generated by Django 5.0 on 2026-04-10 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_produto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categorias',
            field=models.ManyToManyField(blank=True, help_text='Categorias associadas a este produto (ex: "calçado", "roupa", "comida").', related_name='produtos', to='app.categorialoja'),
        ),
    ]
