# Generated by Django 5.0 on 2026-04-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_produto_categorias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loja',
            name='template',
        ),
        migrations.AddField(
            model_name='loja',
            name='dark_mode',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='template_id',
            field=models.CharField(blank=True, default='classico', max_length=50),
        ),
        migrations.AlterField(
            model_name='loja',
            name='cor_primaria',
            field=models.CharField(blank=True, default='#dc2626', max_length=7),
        ),
        migrations.AlterField(
            model_name='loja',
            name='cor_secundaria',
            field=models.CharField(blank=True, default='#1c1c1e', max_length=7),
        ),
    ]
