# Generated by Django 5.0 on 2026-04-18 13:18

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_loja_template_loja_dark_mode_loja_template_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficheiro', models.ImageField(upload_to=app.models.produto_imagem_upload)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('legenda', models.CharField(blank=True, max_length=120)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='app.produto')),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
