# Generated by Django 5.0 on 2026-04-18 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_produtoimagem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemcarrinho',
            unique_together=set(),
        ),
    ]
