# Generated by Django 5.0 on 2026-04-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_itemcarrinho_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='google_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
