// src/config/lojaTemplates.js
// Fonte única de verdade para todos os templates disponíveis.
// Usado em BackofficeTemplates.vue e em LojaPublica.vue para carregar o componente certo.

export const TEMPLATES = [
  {
    id: 'classico',
    nome: 'Clássico',
    descricao: 'Layout versátil com sidebar flutuante. Funciona para qualquer tipo de negócio.',
    categorias: ['todos'],
    tag: 'Versátil',
    primaryDefault: '#dc2626',
    secundariaDefault: '#1c1c1e',
    darkDefault: true,
  },
  {
    id: 'minimalista',
    nome: 'Minimalista',
    descricao: 'Tipografia extrema, espaço máximo, zero ornamentação. A marca fala sozinha.',
    categorias: ['moda', 'luxo'],
    tag: 'Luxury',
    primaryDefault: '#a8a29e',
    secundariaDefault: '#1c1917',
    darkDefault: true,
  },
  {
    id: 'moda-boutique',
    nome: 'Moda Boutique',
    descricao: 'Serif elegante com tons dourados. Para boutiques e marcas premium.',
    categorias: ['moda'],
    tag: 'Fashion',
    primaryDefault: '#b8860b',
    secundariaDefault: '#0a0805',
    darkDefault: true,
  },
  {
    id: 'moda-editorial',
    nome: 'Moda Editorial',
    descricao: 'Layout assimétrico 60/40 com números editoriais. Estética de revista.',
    categorias: ['moda'],
    tag: 'Editorial',
    primaryDefault: '#e4e4e7',
    secundariaDefault: '#09090b',
    darkDefault: true,
  },
  {
    id: 'restaurante-bistro',
    nome: 'Restaurante Bistro',
    descricao: 'Tipografia serif, tons quentes, ornamentos decorativos. Estilo Parisiense.',
    categorias: ['restaurante'],
    tag: 'Food',
    primaryDefault: '#d97706',
    secundariaDefault: '#1a1410',
    darkDefault: false,
  },
  {
    id: 'restaurante-moderno',
    nome: 'Restaurante Moderno',
    descricao: 'Hero cinematográfico com parallax, sidebar de categorias e cards de menu.',
    categorias: ['restaurante'],
    tag: 'Food',
    primaryDefault: '#e11d48',
    secundariaDefault: '#0f0f0f',
    darkDefault: true,
  },
  {
    id: 'tech-store',
    nome: 'Tech Store',
    descricao: 'Dashboard tech com grid overlay, HUD de estatísticas e acento neon.',
    categorias: ['tecnologia'],
    tag: 'Tech',
    primaryDefault: '#06b6d4',
    secundariaDefault: '#020617',
    darkDefault: true,
  },
  {
    id: 'vibrante',
    nome: 'Vibrante',
    descricao: 'Formas geométricas, texto outline, marquee animado. Energia e atitude.',
    categorias: ['moda', 'todos'],
    tag: 'Bold',
    primaryDefault: '#f43f5e',
    secundariaDefault: '#09090b',
    darkDefault: true,
  },
  // ── Novos templates ────────────────────────────────────────────────────────
  {
    id: 'natureza',
    nome: 'Natureza',
    descricao: 'Visual orgânico, tons verdes e terrosos. Para produtos naturais e bio.',
    categorias: ['todos', 'natureza'],
    tag: 'Nature',
    primaryDefault: '#16a34a',
    secundariaDefault: '#051a0a',
    darkDefault: true,
  },
  {
    id: 'luxo-premium',
    nome: 'Luxo Premium',
    descricao: 'Ultra-minimalista, ouro e preto absoluto. Para jóias e marcas de prestígio.',
    categorias: ['moda', 'luxo'],
    tag: 'Premium',
    primaryDefault: '#c9a84c',
    secundariaDefault: '#030303',
    darkDefault: true,
  },
  {
    id: 'desporto',
    nome: 'Desporto',
    descricao: 'Dinâmico, diagonal, alta energia. Para equipamento desportivo e fitness.',
    categorias: ['desporto', 'todos'],
    tag: 'Sport',
    primaryDefault: '#f97316',
    secundariaDefault: '#0a0a0a',
    darkDefault: true,
  },
]

export const CATEGORIAS_FILTRO = [
  { value: 'todos',       label: 'Genérico'    },
  { value: 'moda',        label: 'Moda'        },
  { value: 'luxo',        label: 'Luxo'        },
  { value: 'restaurante', label: 'Restauração' },
  { value: 'tecnologia',  label: 'Tecnologia'  },
  { value: 'desporto',    label: 'Desporto'    },
  { value: 'natureza',    label: 'Natureza'    },
]

// Mapa de componente para LojaPublica.vue usar dynamic import
export const TEMPLATE_COMPONENTS = {
  'classico':            () => import('@/components/templates/TemplateClassico.vue'),
  'minimalista':         () => import('@/components/templates/TemplateMinimalista.vue'),
  'moda-boutique':       () => import('@/components/templates/TemplateModaBoutique.vue'),
  'moda-editorial':      () => import('@/components/templates/TemplateModaEditorial.vue'),
  'restaurante-bistro':  () => import('@/components/templates/TemplateRestauranteBistro.vue'),
  'restaurante-moderno': () => import('@/components/templates/TemplateRestauranteModerno.vue'),
  'tech-store':          () => import('@/components/templates/TemplateTechStore.vue'),
  'vibrante':            () => import('@/components/templates/TemplateVibrante.vue'),
  'natureza':            () => import('@/components/templates/TemplateNatureza.vue'),
  'luxo-premium':        () => import('@/components/templates/TemplateLuxoPremium.vue'),
  'desporto':            () => import('@/components/templates/TemplateDesporto.vue'),
}
